### ISSUE TITLE
Add support for warps injectedArweaveSigner plugin

### ISSUE THREAD

**Issue by george-e-d-g-e** [labscommunity/arweavekit#80] opened 2023-09-20 10:29 UTC
Ran into an issue when using `writeContract` from an arConnect wallet in the browser.

`"Uncaught (in promise) Error: Signer not set correctly. If you connect wallet through 'use_wallet', please remember that it only works when bundling is disabled."`

![image](https://github.com/labscommunity/arweavekit/assets/47055562/c8d6bc7c-27f1-4d54-91d6-2c676c92dae1) 

Would be fantastic to support the [injectedArweaveSigner plugin](https://academy.warp.cc/docs/sdk/advanced/plugins/signature) with arweavekit so transactions could be bundled and sequenced by warp.

:heart:

**Comment by pawanpaudel93** [comment] 2023-09-20 10:48
Hello @george-e-d-g-e, Appreciate your report! We're actively working on adding support for various signers including `InjectedArweaveSigner ` in the upcoming version. Stay tuned for updates and feel free to share any additional thoughts or questions. Thanks again!"

**Comment by pawanpaudel93** [comment] 2023-09-22 13:15
Hello @george-e-d-g-e, New version `1.5.0` has been released. Now the `EthereumSigner, InjectedEthereumSigner, ArweaveSigner, and InjectedArweaveSigner` are supported so you can pass `Arweave JWK or Ethereum private key` to the `wallet` param and If you don't pass the `wallet` param at all in the browser environment, first `Ethereum signer` will be used if Ethereum wallet like metamask is present or if failed/canceled, `Arweave signer` will be used. You can also pass strategies like `arweave`, `ethereum`, or `both` (default) on what wallet to use in the browser environment.


For example, you can run your above code example as:

```ts
import { writeContract } from 'arweavekit/contract'

// when calling writeContract add the useInjectedArweaveSigner function
await writeContract({
    contractTxId,
    options: {
      function: "someContractFunction",
    },
    environment,
    strategy: "arweave"
})
}
```

Please feel free to leave a comment if you encounter any issues during this process. Additionally, once the issue is resolved, kindly consider closing it.

**Closed** 2023-09-25 07:02 UTC

**Comment by george-e-d-g-e** [comment] 2023-09-25 07:03
Fantastic 😊 this looks great!
